.github/workflows/deploy_to_qa.yaml, app/frontend/Dockerfile
=> COWER-32: Add frontend to deploy pipeline

app/frontend/src/components/modals/PlaceInfoModal.tsx, app/frontend/src/index.tsx, app/frontend/src/redux/actions.ts, app/frontend/src/redux/index.ts, app/frontend/src/redux/orderSlice.ts, app/frontend/src/routes/checkout-page.tsx, app/frontend/src/routes/home-page.tsx, app/frontend/src/routes/payment-result-page.tsx, app/frontend/src/security/OrderPresentLayout.tsx, app/frontend/src/styles/GlobalStyle.ts, app/frontend/src/styles/overrides.ts, app/frontend/src/types/Order.ts, app/frontend/src/types/PlaceInfo.ts
=> COWER-33: Add checkout page

app/frontend/src/components/modals/PlaceInfoModal.tsx, app/frontend/src/index.tsx, app/frontend/src/redux/actions.ts, app/frontend/src/redux/index.ts, app/frontend/src/redux/ordersSlice.ts, app/frontend/src/routes/checkout-page.tsx, app/frontend/src/routes/orders-page.tsx, app/frontend/src/routes/payment-result-page.tsx, app/frontend/src/types/Order.ts, app/frontend/src/utils/formatOrderTime.ts
=> COWER-34: Add payment result page

.github/workflows/deploy_to_qa.yaml, app/frontend/index.html, app/frontend/package-lock.json, app/frontend/package.json, app/frontend/src/components/forms/SignInForm.tsx, app/frontend/src/routes/checkout-page.tsx, app/frontend/src/routes/home-page.tsx
=> COWER-39: add metrics on register and create order

app/frontend/src/api.ts
=> COWER-42: Read backend address from env variable

app/backend/Cower.Web/Controllers/UserController.cs, app/backend/Cower.Web/ErrorCodes.cs, app/backend/Cower.Web/Helpers/ValidationHelper.cs, app/backend/Cower.Web/Models/ErrorDTO.cs, app/backend/Cower.Web/Models/LoginRequestDTO.cs
=> COWER-57: Add request validation and error handling for /api/user/login

app/backend/Cower.Web/Controllers/UserController.cs, app/backend/Cower.Web/ErrorCodes.cs, app/backend/Cower.Web/Models/ErrorDTO.cs, app/backend/Cower.Web/Program.cs, app/backend/Cower.Web/StatusCodeHandlers/ForbiddenHandler.cs, app/backend/Cower.Web/StatusCodeHandlers/ServerErrorHandler.cs, app/backend/Cower.Web/StatusCodeHandlers/UnauthorizedHandler.cs
=> COWER-59: Add handling of responses with codes 401, 403 and 500

app/backend/Cower.Data/Repositories/ICoworkingRepository.cs, app/backend/Cower.Data/Repositories/IUserRepository.cs, app/backend/Cower.Data/Repositories/Implementation/CoworkingRepository.cs, app/backend/Cower.Data/Repositories/Implementation/UserRepository.cs, app/backend/Cower.Domain/Models/Coworking/Coworking.cs, app/backend/Cower.Domain/Models/Coworking/CoworkingWorkingTime.cs, app/backend/Cower.Service/Extensions/CoworkingEntityExtension.cs, app/backend/Cower.Service/Extensions/CoworkingWorkingTimeEntityExtension.cs, app/backend/Cower.Service/Extensions/IntExtension.cs, app/backend/Cower.Service/Extensions/RoleEntityExt.cs, app/backend/Cower.Service/Extensions/UserEntityExt.cs, app/backend/Cower.Service/Services/ICoworkingService.cs, app/backend/Cower.Service/Services/IUserService.cs, app/backend/Cower.Service/Services/Implementation/CoworkingService.cs, app/backend/Cower.Service/Services/Implementation/UserService.cs, app/backend/Cower.Web/Controllers/CoworkingController.cs, app/backend/Cower.Web/Controllers/UserController.cs, app/backend/Cower.Web/ErrorCodes.cs, app/backend/Cower.Web/Helpers/ValidationHelper.cs, app/backend/Cower.Web/Models/CoworkingResponseDTO.cs, app/backend/Cower.Web/Models/CoworkingWorkingTimeResponseDTO.cs, app/backend/Cower.Web/Program.cs
=> COWER-49: Coworking info endpoint

app/frontend/src/api.ts, app/frontend/src/components/forms/SignInForm.tsx
=> COWER-55: Add fields validation and error handling to sign in page

app/backend/Cower.Data/Migrations/20240509184640_AddBookingDateColumn.Designer.cs, app/backend/Cower.Data/Migrations/20240509184640_AddBookingDateColumn.cs, app/backend/Cower.Data/Models/BookingTimeSlotDAL.cs, app/backend/Cower.Data/Models/Entities/BookingEntity.cs, app/backend/Cower.Data/Repositories/IBookingRepository.cs, app/backend/Cower.Data/Repositories/ICoworkingRepository.cs, app/backend/Cower.Data/Repositories/Implementation/BookingRepository.cs, app/backend/Cower.Data/Repositories/Implementation/CoworkingRepository.cs, app/backend/Cower.Service/Extensions/CoworkingEntityExtension.cs, app/backend/Cower.Service/Extensions/CoworkingWorkingTimeEntityExtension.cs, app/backend/Cower.Service/Extensions/LinkedListExtensions.cs, app/backend/Cower.Service/Models/CoworkingSeatsAvailavilityResponseBL.cs, app/backend/Cower.Service/Services/ICoworkingService.cs, app/backend/Cower.Service/Services/Implementation/CoworkingService.cs, app/backend/Cower.Web/Attributes/DateOnlyAttribute.cs, app/backend/Cower.Web/Controllers/CoworkingController.cs, app/backend/Cower.Web/Models/CoworkingSeatAvailabilityRequestDTO.cs, app/backend/Cower.Web/Models/CoworkingSeatAvailabiltiyResponseDTO.cs, app/backend/Cower.Web/Models/CoworkingSeatTimeSlotResponseDTO.cs, app/backend/Cower.Web/Program.cs
=> COWER-51: Add seat availability endpoint

app/backend/Cower.Data/Repositories/ICoworkingRepository.cs, app/backend/Cower.Data/Repositories/Implementation/CoworkingRepository.cs, app/backend/Cower.Service/Services/ICoworkingService.cs, app/backend/Cower.Service/Services/Implementation/CoworkingService.cs, app/backend/Cower.Web/Controllers/CoworkingController.cs, app/backend/Cower.Web/Models/CoworkingResponseDTO.cs, app/backend/Cower.Web/Models/CoworkingsResponseDTO.cs
=> COWER-60: All coworkings endpoint

.github/workflows/deploy_to_prod.yaml, .github/workflows/deploy_to_qa.yaml
=> COWER-70: Add backend environment variables for YooMoney integration

app/frontend/index.html, app/frontend/src/components/forms/SignUpForm.tsx, app/frontend/src/components/modals/PlaceInfoModal.tsx, app/frontend/src/components/ui/StyledSelect.tsx, app/frontend/src/redux/orderSlice.ts, app/frontend/src/redux/ordersSlice.ts, app/frontend/src/routes/checkout-page.tsx, app/frontend/src/routes/home-page.tsx, app/frontend/src/routes/orders-page.tsx, app/frontend/src/routes/payment-result-page.tsx, app/frontend/src/security/UserOnlyLayout.tsx, app/frontend/src/styles/overrides.ts, app/frontend/src/types/Booking.ts, app/frontend/src/types/Coworking.ts, app/frontend/src/types/PlaceInfo.ts, app/frontend/src/types/api/SeatAvailability.ts, app/frontend/tsconfig.json
=> COWER-52, COWER-53, COWER-54: Display coworking, floor and seats info

app/frontend/src/routes/checkout-page.tsx, app/frontend/src/routes/home-page.tsx, app/frontend/src/types/Booking.ts
=> COWER-67: Rework checkout page to use api

app/backend/Cower.Web/Cower.Web.csproj, app/backend/Cower.Web/Program.cs, app/backend/Cower.Web/appsettings.Development.json, app/backend/Cower.Web/appsettings.json
=> COWER-73: Write backend logs to file

app/frontend/index.html, app/frontend/src/components/forms/SignInForm.tsx, app/frontend/src/components/forms/SignUpForm.tsx, app/frontend/src/components/modals/PlaceInfoModal.tsx, app/frontend/src/index.tsx, app/frontend/src/routes/home-page.tsx, app/frontend/src/styles/overrides.ts, app/frontend/src/types/Coworking.ts, app/frontend/src/types/PlaceInfo.ts
=> COWER-85: Frontend floor model

app/backend/Cower.Data/Extensions/CoworkingSeatEntityExt.cs, app/backend/Cower.Data/Migrations/20240527214054_UniqueSeatNumber.Designer.cs, app/backend/Cower.Data/Migrations/20240527214054_UniqueSeatNumber.cs, app/backend/Cower.Data/Models/AddCoworkingSeatDal.cs, app/backend/Cower.Data/Models/CoworkingSeatDal.cs, app/backend/Cower.Data/Models/Entities/CoworkingSeatEntity.cs, app/backend/Cower.Data/Models/UpdateCoworkingSeatDal.cs, app/backend/Cower.Data/Repositories/ISeatRepository.cs, app/backend/Cower.Data/Repositories/Implementation/SeatRepository.cs, app/backend/Cower.Service/Exceptions/FloorDoesntExistException.cs, app/backend/Cower.Service/Exceptions/SeatNumberExistOnFloorException.cs, app/backend/Cower.Service/Models/CreateSeatBl.cs, app/backend/Cower.Service/Models/UpdateSeatBl.cs, app/backend/Cower.Service/Services/ISeatService.cs, app/backend/Cower.Service/Services/Implementation/BookingService.cs, app/backend/Cower.Service/Services/Implementation/SeatService.cs, app/backend/Cower.Web/Controllers/FloorController.cs, app/backend/Cower.Web/Controllers/SeatController.cs, app/backend/Cower.Web/ErrorCodes.cs, app/backend/Cower.Web/Models/Coworking/CoworkingSeatsDto.cs, app/backend/Cower.Web/Models/Coworking/CreateCoworkingSeatDto.cs, app/backend/Cower.Web/Models/Coworking/UpdateCoworkingSeatDto.cs, app/backend/Cower.Web/Program.cs
=> COWER-75: Add seats controller

app/backend/Cower.Data/Models/AddCoworkingDal.cs, app/backend/Cower.Data/Models/AddCoworkingSeatDal.cs, app/backend/Cower.Data/Models/AddCoworkingWorkingTimeDal.cs, app/backend/Cower.Data/Models/UpdateCoworkingDal.cs, app/backend/Cower.Data/Models/UpdateCoworkingWorkingTimeDal.cs, app/backend/Cower.Data/Repositories/ICoworkingRepository.cs, app/backend/Cower.Data/Repositories/Implementation/CoworkingRepository.cs, app/backend/Cower.Service/Extensions/IntExtension.cs, app/backend/Cower.Service/Models/CreateCoworkingBl.cs, app/backend/Cower.Service/Models/CreateCoworkingWorkingTimeBl.cs, app/backend/Cower.Service/Models/UpdateCoworkingBl.cs, app/backend/Cower.Service/Models/UpdateCoworkingWorkingTimeBl.cs, app/backend/Cower.Service/Services/ICoworkingService.cs, app/backend/Cower.Service/Services/Implementation/CoworkingService.cs, app/backend/Cower.Web/Attributes/DayOfWeekAttribute.cs, app/backend/Cower.Web/Controllers/CoworkingController.cs, app/backend/Cower.Web/Controllers/FloorController.cs, app/backend/Cower.Web/Controllers/SeatController.cs, app/backend/Cower.Web/Controllers/UserController.cs, app/backend/Cower.Web/Extensions/CoworkingExt.cs, app/backend/Cower.Web/Models/Coworking/CreateCoworkingDto.cs, app/backend/Cower.Web/Models/Coworking/CreateCoworkingWorkingTimeDto.cs, app/backend/Cower.Web/Models/Coworking/UpdateCoworkingDto.cs, app/backend/Cower.Web/Models/Coworking/UpdateCoworkingWorkingTimeDto.cs, app/frontend/src/components/forms/SignInForm.tsx, app/frontend/src/components/forms/SignUpForm.tsx, app/frontend/src/routes/home-page.tsx, app/frontend/src/routes/root.tsx
=> COWER-76: Add coworking modify endpoints

app/backend/Cower.Data/Repositories/IBookingRepository.cs, app/backend/Cower.Data/Repositories/Implementation/BookingRepository.cs, app/backend/Cower.Domain/Models/User.cs, app/backend/Cower.Service/Extensions/UserEntityExt.cs, app/backend/Cower.Service/Services/IBookingService.cs, app/backend/Cower.Service/Services/Implementation/BookingService.cs, app/backend/Cower.Web/Controllers/BookingController.cs, app/backend/Cower.Web/Controllers/UserController.cs
=> COWER-79: Admin get bookings endpoint

.github/workflows/deploy_to_prod.yaml, .github/workflows/deploy_to_qa.yaml, app/backend/Cower.Service/Services/Implementation/YoomoneyService.cs
=> COWER-93: Fix yoomoney success url

app/backend/Cower.Data/Repositories/IBookingRepository.cs, app/backend/Cower.Data/Repositories/Implementation/BookingRepository.cs, app/backend/Cower.Domain/Models/Statistics/BookingsCountStatistic.cs, app/backend/Cower.Domain/Models/Statistics/BookingsPriceStatistic.cs, app/backend/Cower.Domain/Models/Statistics/StatisticsStep.cs, app/backend/Cower.Service/Extensions/StatisticsStepExt.cs, app/backend/Cower.Service/Services/IBookingService.cs, app/backend/Cower.Service/Services/IStatisticsService.cs, app/backend/Cower.Service/Services/Implementation/StatisticsService.cs, app/backend/Cower.Web/Controllers/StatisticsController.cs, app/backend/Cower.Web/Models/Statistics/BookingsCountStatisticsResponseDto.cs, app/backend/Cower.Web/Models/Statistics/BookingsPriceStatisticsResponseDto.cs, app/backend/Cower.Web/Models/Statistics/StatisticsRequestDto.cs, app/backend/Cower.Web/Program.cs
=> COWER-78: Add statistics endpoints

app/backend/Cower.Data/Models/UpdateUserDal.cs, app/backend/Cower.Data/Repositories/IBookingRepository.cs, app/backend/Cower.Data/Repositories/IUserRepository.cs, app/backend/Cower.Data/Repositories/Implementation/BookingRepository.cs, app/backend/Cower.Data/Repositories/Implementation/UserRepository.cs, app/backend/Cower.Domain/Models/Statistics/BookingsCountStatistic.cs, app/backend/Cower.Domain/Models/Statistics/BookingsPriceStatistic.cs, app/backend/Cower.Domain/Models/Statistics/StatisticsStep.cs, app/backend/Cower.Service/Extensions/StatisticsStepExt.cs, app/backend/Cower.Service/Models/UpdateUserBl.cs, app/backend/Cower.Service/Services/IBookingService.cs, app/backend/Cower.Service/Services/IStatisticsService.cs, app/backend/Cower.Service/Services/IUserService.cs, app/backend/Cower.Service/Services/Implementation/StatisticsService.cs, app/backend/Cower.Service/Services/Implementation/UserService.cs, app/backend/Cower.Web/Controllers/StatisticsController.cs, app/backend/Cower.Web/Controllers/UserController.cs, app/backend/Cower.Web/Models/Statistics/BookingsCountStatisticsResponseDto.cs, app/backend/Cower.Web/Models/Statistics/BookingsPriceStatisticsResponseDto.cs, app/backend/Cower.Web/Models/Statistics/StatisticsRequestDto.cs, app/backend/Cower.Web/Models/UpdateUserDto.cs, app/backend/Cower.Web/Program.cs
=> COWER-91: Add modify user endpoint

.github/workflows/deploy_to_prod.yaml, .github/workflows/deploy_to_qa.yaml, app/backend/Cower.Data/ApplicationContext.cs, app/backend/Cower.Data/Extensions/PasswordResetTokenEntityExt.cs, app/backend/Cower.Data/Extensions/UserEntityExt.cs, app/backend/Cower.Data/Migrations/20240614213038_AddPasswordResetTokenTable.Designer.cs, app/backend/Cower.Data/Migrations/20240614213038_AddPasswordResetTokenTable.cs, app/backend/Cower.Data/Models/Entities/PasswordResetTokenEntity.cs, app/backend/Cower.Data/Models/PasswordResetTokenDal.cs, app/backend/Cower.Data/Repositories/IPasswordResetTokenRepository.cs, app/backend/Cower.Data/Repositories/IUserRepository.cs, app/backend/Cower.Data/Repositories/Implementation/PasswordResetTokenRepository.cs, app/backend/Cower.Data/Repositories/Implementation/UserRepository.cs, app/backend/Cower.Domain/Models/PasswordResetToken.cs, app/backend/Cower.Service/Cower.Service.csproj, app/backend/Cower.Service/Exceptions/ExpiredPasswordResetTokenException.cs, app/backend/Cower.Service/Exceptions/PasswordResetTokenDoesntExistException.cs, app/backend/Cower.Service/Extensions/PasswordResetTokenDalExt.cs, app/backend/Cower.Service/Services/IEmailService.cs, app/backend/Cower.Service/Services/IPasswordResetTokenService.cs, app/backend/Cower.Service/Services/IUserService.cs, app/backend/Cower.Service/Services/Implementation/EmailService.cs, app/backend/Cower.Service/Services/Implementation/PasswordResetTokenService.cs, app/backend/Cower.Service/Services/Implementation/UserService.cs, app/backend/Cower.Web/Controllers/UserController.cs, app/backend/Cower.Web/ErrorCodes.cs, app/backend/Cower.Web/Models/PasswordResetDto.cs, app/backend/Cower.Web/Models/SendPasswordResetTokenDto.cs, app/backend/Cower.Web/Program.cs
=> COWER-87: Add password reset endpoints

app/backend/Cower.Service/Services/Implementation/BookingService.cs
=> COWER-90: Add check for booking time

app/frontend/src/components/modals/PlaceInfoModal.tsx, app/frontend/src/components/ui/MapLoader.tsx, app/frontend/src/routes/checkout-page.tsx, app/frontend/src/routes/home-page.tsx, app/frontend/src/types/Booking.ts, app/frontend/src/types/PlaceInfo.ts, app/frontend/src/utils/formatOrderTime.ts
=> COWER-97: Home page loader

app/frontend/src/routes/checkout-page.tsx, app/frontend/src/routes/home-page.tsx
=> COWER-94: Additional metrics

app/frontend/src/components/forms/SignInForm.tsx, app/frontend/src/components/forms/SignUpForm.tsx, app/frontend/src/index.tsx, app/frontend/src/routes/reset-password-page.tsx
=> COWER-88: Reset password page

app/frontend/src/routes/profile-page.tsx
=> COWER-92: Add profile edit page

app/frontend/src/components/BookingItem.tsx, app/frontend/src/routes/checkout-page.tsx, app/frontend/src/routes/orders-page.tsx, app/frontend/src/routes/payment-result-page.tsx, app/frontend/src/types/Booking.ts, app/frontend/src/utils/getTimeDelta.ts
=> COWER-82: Manage bookings page
